### ISSUE TITLE
IP question

### ISSUE THREAD

**Issue by ramonfincken** [timnashcouk/tn-tame-session-defaults#2]
You check for $_SERVER['REMOTE_ADDR'] 

what about forwarded IP's ?

**Comment by timnashcouk** [comment]
It's mirroring the check in WordPress own session token manager
```
                // IP address.
                if ( ! empty( $_SERVER['REMOTE_ADDR'] ) ) {
                        $session['ip'] = $_SERVER['REMOTE_ADDR'];
                }

```
https://github.com/WordPress/wordpress-develop/blob/8ee7651d0e953f0bdc5705bb5359f4067fefa89b/src/wp-includes/class-wp-session-tokens.php#L137C3-L141C1

We want to make sure we are matching, what WordPress is storing, otherwise we will get a false positive

**Comment by ramonfincken** [comment]
good design-choise
